scss_files: 'assets/css/**/*.scss'

exclude:
  - 'assets/css/vendor/*'
  - 'assets/css/partials/_reset.scss'

linters:
  ColorVariable:
    exclude:
      - 'assets/css/partials/_buttons.scss'

  ElsePlacement:
    enabled: true
    style: new_line

  HexLength:
    enabled: true
    style: long

  HexNotation:
    style: uppercase

  Indentation:
    severity: warning
    width: 4

  LeadingZero:
    style: include_zero

  NameFormat:
    enabled: false

  SelectorFormat:
    enabled: false
    convention: ^\.(_)?[a-z]+-[a-z0-9-]+((_{2}|-{2})?[a-z0-9-]+)?(-{2}[a-z0-9-]+)?[a-z0-9]$

  SingleLinePerSelector:
    allow_single_line_rule_sets: true
